### ISSUE TITLE
Use a more meaningful templating name other than "foo" during parsing

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/modelmesh-serving#114]
similar to issue https://github.com/opendatahub-io/data-science-pipelines-operator/issues/16, here we name template as "foo" which should be improved to be something more meaningful when gets failure in the printout logs.

**Comment by zdtsw** [comment]
line https://github.com/opendatahub-io/modelmesh-serving/blob/a14b7c840b597bf40146fd8d307c5c1715232596/controllers/config/templating.go#L52
i would not say it is a bug but  a low priority good to have issue, just rename it for better logging

**Comment by israel-hdez** [comment]
Fixed.
