### ISSUE TITLE
Update OVMS to v2023.1

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/modelmesh-serving#137]
Currently OVMS we use is v2022 (see: [modh](https://quay.io/repository/modh/openvino-model-server?tab=tags) image, and [odh image](https://quay.io/repository/opendatahub/openvino_model_server?tab=tags) )

These images are built in openshift-ci from [this](https://github.com/openshift/release/blob/master/ci-operator/config/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-v2022.3-release.yam) yaml file.
As can be seen in this yaml file (see line 233), openshift-ci builds the image based on our downstream [repo](https://github.com/red-hat-data-services/openvino_model_server/tree/v2022.3-release).

We need to create a new yaml file in openshift-ci that will build the v2023 version of OVMS based on the [v2023 branch](https://github.com/red-hat-data-services/openvino_model_server/tree/2023.0-release) of our downstream repo. OpenShift-ci yaml replicates the logic/instructions of the Dockerfiles in our downstream repo (ie. [Dockerfile.redhat](https://github.com/red-hat-data-services/openvino_model_server/blob/2023.0-release/Dockerfile.redhat))

Deliverable:
- [ ] Quay image of OVMS v2023.1

**Comment by Xaenalt** [comment]
Attempt with https://github.com/openvinotoolkit/model_server/pull/1958/files#diff-507d73bbefd62da3db1eec3a006d6f4bf47433fec017a5299f63921bd0a605b0

**Comment by Xaenalt** [comment]
2023.1 branch: https://github.com/opendatahub-io/openvino_model_server/tree/2023.1-release

**Comment by rpancham** [comment]
Add openvino model server ci operator config file of v2023.1
https://github.com/openshift/release/pull/43854

**Comment by rpancham** [comment]
add build_args to ci operator file of v2023.1
[](https://github.com/openshift/release/pull/43854)

**Comment by rpancham** [comment]
Fixed the image failing 
https://github.com/openshift/release/pull/44515

**Comment by heyselbi** [comment]
2023.1 image: quay.io/opendatahub/openvino_model_server:stable

**Comment by heyselbi** [comment]
Follow up issue: https://github.com/opendatahub-io/modelmesh-serving/issues/246
