### ISSUE TITLE
Create JupyterNotebooks for ModelMeshServing Quickstarts

### ISSUE THREAD

**Issue by mholder6** [opendatahub-io/modelmesh-serving#141]
Currently there are no real hints on how to use model serving service.  User needs to know how I can take my Python in a notebook using this model, to a request.  What does that look like? Develop a sample notebook to do the calls internal/external.

**Comment by taneem-ibrahim** [comment]
@mholder6 could you please link your PRs to this tracker?

**Comment by heyselbi** [comment]
All Mariah's docs instructions are here: https://drive.google.com/drive/folders/1W9uPLk1X3-OHVtY8iGkn6CmNWDcWpJaF?usp=drive_link
Will need to add them into the repo. Will prioritize after 1.33/1.34 sprints.

**Comment by spolti** [comment]
closing since there is no interaction in this issue and related PRs, if you still need to have this contribution added, feel free to reopen it.

Thanks.
