### ISSUE TITLE
github workflow fvt.yaml broken

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/modelmesh-serving#151]
**Describe the bug**

https://github.com/opendatahub-io/modelmesh-serving/blob/main/.github/workflows/fvt.yml#L112

**To Reproduce**

That happended during [latest upstream sync](https://github.com/opendatahub-io/modelmesh-serving/commit/58d9660a7a54813a66e228f84ad895e5b0d2e54b#diff-00424bef35413fbfaf1f11c45c0dc7eff3948fe827e78789b1797ed0ed7eccaa)

leading to this PR error

https://github.com/opendatahub-io/modelmesh-serving/actions/runs/5682570463

**Expected behavior**

github actions run through

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

Related to PR https://github.com/opendatahub-io/modelmesh-serving/pull/150

**Comment by Jooho** [comment]
@shalberd sorry for the late response. we disable gitaction for modelmesh-serving in opendatahub. So we don't need to change this.
