### ISSUE TITLE
SPIKE: Create JIRA ticket from all 1.32 issues and PRs

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/modelmesh-serving#166]

**Comment by taneem-ibrahim** [comment]
@heyselbi Should we consider adding this by default to each sprint and rotate the task among the team members?

**Comment by heyselbi** [comment]
Sure, I'll do it for 1.32 and write out the instructions. Then I'll add it to the template we already had about the upstream syncing. This could be one of the steps when closing a sprint and starting a new one.

**Comment by heyselbi** [comment]
JIRA: https://issues.redhat.com/browse/RHODS-10590

Will add it into a template for each sprint
and
Will create a follow up ticket to look into automation of this
