### ISSUE TITLE
[SPIKE] Assist UX/UI for KServe/ModelMesh experience

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/modelmesh-serving#193]
This is to address the req 17:
**17. Support options for KServe and/or ModelMesh (support KServe - 1 model per pod or modelmesh - multiple models per pod)**
  a. P0: RHODS admins should be able to configure whether they want to use KServe (single model serving + additional functionality), ModelMesh, or both

- This would be a cluster-level setting
  - Need to clearly communicate the differences between KServe and MM - don’t need to refer to the open source project names, but rather describe the functional differences 
- Default option for new customers would be KServe only
- If only one option, potential to streamline / simplify the UI
  - ModelMesh - need to configure model server
  - KServe - do we need the model server UI? Would all the options be available in UI for deploying a single model?
- If admins want to make both options available, users would choose between KServe & MM in a project
- All existing customers should have no change in functionality upon migration (eg. likely MM only)
- Changes to cluster setting would be applied on a move forward basis (newly created projects). No changes to existing projects.

Acceptance criteria:

- [ ] Set up a meeting with UX/UI teams to identify the issues that would need to be addressed
- [ ] (optional) If needed, set up follow up meetings to consult and guide the UX/UI teams on req 17
- [ ] Create follow up issues that would require Dev work

**Comment by Jooho** [comment]
related ticket:
- https://docs.google.com/document/d/1izyc2sjMYcIcxLpY1MlMnpXUN_Xx1i7zw7GEH5Be4Zo/edit#heading=h.6vnzm6szhu4j

**Comment by heyselbi** [comment]
Closing it as we already have a daily meeting set up with UI.
