### ISSUE TITLE
[STORY] ModelMesh manifests transition readiness for ODH v2

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/modelmesh-serving#207]
Tasklist: 

- [x] https://github.com/opendatahub-io/odh-model-controller/issues/87 

**References:**
Following is a Dev Build that can be used to test your release manifests directly from component repos using updated api:
- CatalogSource: quay.io/vhire/opendatahub-operator-catalog:v2.3.0-1
- Example
~~~
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default
spec:
  components:
    dashboard:
      managementState: "Managed"
      devFlags:
        manifests:
          - manifestsFolder: manifests
            overlay: overlays/incubation
            uri: https://github.com/opendatahub-io/odh-dashboard/tarball/v2.15.0-incubation

    # Example of component that references multiple repos
    kserve:
      managementState: "Managed"
      devFlags:
        manifests:
          - manifestsFolder: config
            overlay: overlays/odh
            uri: 'https://github.com/opendatahub-io/kserve/tarball/master'
          - manifestsFolder: config
            uri: https://github.com/opendatahub-io/odh-model-controller/tarball/main
~~~

**Comment by heyselbi** [comment]
@VedantMahabaleshwarkar could you add the PRs here and close this issue?

**Comment by VedantMahabaleshwarkar** [comment]
PRs from other repos also included in this story (can't link PRs from other repos in the github field) 
https://github.com/opendatahub-io/odh-model-controller/pull/92 
https://github.com/opendatahub-io/opendatahub-operator/pull/639
