### ISSUE TITLE
Add Periodic rebuilds for main/stable branches in Openshift-CI

### ISSUE THREAD

**Issue by rpancham** [opendatahub-io/modelmesh-serving#257]
This task covers adding a periodic rebuild for OVMS images on the main/stable branches to cover dependency updates. This rebuild should take place weekly

- [ ] Weekly rebuilds on 2023.1-release branch
- [ ] Weekly rebuilds on main branch

**Comment by Xaenalt** [comment]
Closing since it's in the wrong project
