### ISSUE TITLE
Remove servingruntimes_config.yaml from the manifest folder

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/modelmesh-serving#58]
**Describe the bug**

We are gonna start using servingruntimes_config.yaml as the file for dynamic spec of the serving runtime, managed by the deployer downstream, we don't want the operator to reconcile this file.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by heyselbi** [comment]
@lucferbux is this still an issue?

**Comment by lucferbux** [comment]
@heyselbi thanks for the ping, yeah, we deprecated it and it's already removed from the source code. Closing the task.
