### ISSUE TITLE
Replace app: modelmesh label with component: model-mesh-etcd

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/modelmesh-serving#59]
**Describe the bug**

A change of label from `app: modelmesh` to `component: model-mesh-etcd` has been initiated but not completed. `app: modelmesh` is still used by etcd and is mentioned in `kustomization.yaml`

**Additional context**

@Jooho FYI

**Comment by Jooho** [comment]
Right Selbi. This should be done to replace the old label to new one correctly.
